server:
  port: 8888
spring:
  h2:
    console:
      enabled: true
  cloud:
    discovery:
      enabled: true
    config:
      server:
        git:
          uri: https://github.com/chaouredha/rcfactory-configuration.git
          default-label: main
  application:
    name: CONFIGURATION-SERVICE

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
management:
  endpoint:
    env:
      post:
        enabled: true
